CREATE SCHEMA MASTER_DATA;

DROP TABLE MASTER_DATA.AR_ITEM_CLOSED CASCADE;

CREATE CACHED TABLE MASTER_DATA.AR_ITEM_CLOSED
(
   CMPCODE       VARCHAR(4)    NOT NULL,
   CUSTID        VARCHAR(32)   NOT NULL,
   DOCTYPE       VARCHAR(32)   NOT NULL,
   DOCSUBTYPE    VARCHAR(8),
   DOCNUM        DOUBLE        NOT NULL,
   SOURCESYS     VARCHAR(32),
   INVOICEREF    VARCHAR(32),
   GLACCT        DOUBLE,
   DOCDATE       TIMESTAMP,
   POSTDATE      TIMESTAMP,
   CLEARDATE     TIMESTAMP,
   DOCDESC       VARCHAR(48),
   XACTREF       VARCHAR(32),
   CUSTREF       VARCHAR(32),
   EXTREF5       VARCHAR(32),
   DOCCURR       VARCHAR(3),
   HOMECURR      VARCHAR(3),
   ALTCURR       VARCHAR(3),
   ORGVAL_DOC    DOUBLE,
   ORGVAL_HOME   DOUBLE,
   ORGVAL_ALT    DOUBLE,
   ORGVAL_NORM   DOUBLE,
   OPENVAL_DOC   DOUBLE,
   OPENVAL_HOME  DOUBLE,
   OPENVAL_ALT   DOUBLE,
   OPENVAL_NORM  DOUBLE,
   LASTMOD       TIMESTAMP,
   PAYVAL_DOC    DOUBLE,
   PAYVAL_HOME   DOUBLE,
   PAYVAL_ALT    DOUBLE,
   PAYVAL_NORM   DOUBLE
);

ALTER TABLE MASTER_DATA.AR_ITEM_CLOSED
   ADD PRIMARY KEY (CMPCODE, DOCTYPE, DOCNUM, CUSTID);

DROP TABLE MASTER_DATA.AR_ITEM_MASTER CASCADE;

CREATE CACHED TABLE MASTER_DATA.AR_ITEM_MASTER
(
   CMPCODE       VARCHAR(4)    NOT NULL,
   CUSTID        VARCHAR(32)   NOT NULL,
   DOCTYPE       VARCHAR(32)   NOT NULL,
   DOCSUBTYPE    VARCHAR(8),
   DOCNUM        DOUBLE        NOT NULL,
   SOURCESYS     VARCHAR(32),
   INVOICEREF    VARCHAR(32),
   GLACCT        DOUBLE,
   DOCDATE       TIMESTAMP,
   POSTDATE      TIMESTAMP,
   CLEARDATE     TIMESTAMP,
   DOCDESC       VARCHAR(48),
   XACTREF       VARCHAR(32),
   CUSTREF       VARCHAR(32),
   EXTREF5       VARCHAR(32),
   DOCCURR       VARCHAR(3),
   HOMECURR      VARCHAR(3),
   ALTCURR       VARCHAR(3),
   ORGVAL_DOC    DOUBLE,
   ORGVAL_HOME   DOUBLE,
   ORGVAL_ALT    DOUBLE,
   ORGVAL_NORM   DOUBLE,
   OPENVAL_DOC   DOUBLE,
   OPENVAL_HOME  DOUBLE,
   OPENVAL_ALT   DOUBLE,
   OPENVAL_NORM  DOUBLE,
   LASTMOD       TIMESTAMP,
   PAYVAL_DOC    DOUBLE,
   PAYVAL_HOME   DOUBLE,
   PAYVAL_ALT    DOUBLE,
   PAYVAL_NORM   DOUBLE
);

ALTER TABLE MASTER_DATA.AR_ITEM_MASTER
   ADD PRIMARY KEY (CMPCODE, DOCTYPE, DOCNUM, CUSTID);

DROP TABLE MASTER_DATA.CUSTOMERS CASCADE;

CREATE CACHED TABLE MASTER_DATA.CUSTOMERS
(
   CUSTID      VARCHAR(32)            NOT NULL,
   NAME        VARCHAR(1024),
   ADD1        VARCHAR(1024),
   ADD2        VARCHAR(1024),
   ADD3        VARCHAR(1024),
   CITY        VARCHAR(1024),
   STATEPROV   VARCHAR(16),
   COUNTRY     VARCHAR(32),
   POSTCODE    VARCHAR(32),
   CREATEDATE  BIGINT,
   TERMS       TINYINT,
   CREDITLIM   BIGINT,
   TTMREV      DECIMAL(65535,32767),
   SFID        VARCHAR(64),
   CORPCODE    CHAR(1),
   CRLIMDATE   BIGINT,
   ACCTSTAT    CHAR(1),
   ACCTTYPE    CHAR(1),
   BONDTYPE    CHAR(1),
   PREVCO      CHAR(2),
   SIC         CHAR(4),
   CST         VARCHAR(32),
   CSM         VARCHAR(128),
   MSD         VARCHAR(128),
   SC          VARCHAR(128),
   WAIVERTYPE  VARCHAR(256),
   INVCURR     CHAR(3),
   CREDITCODE  VARCHAR(3),
   LANGUAGE    VARCHAR(32),
   PARENT      VARCHAR(32),
   REMITTO     TINYINT,
   REMARKS1    VARCHAR(128),
   REMARKS2    VARCHAR(128),
   LASTMOD     TIMESTAMP
);

ALTER TABLE MASTER_DATA.CUSTOMERS
   ADD PRIMARY KEY (CUSTID);

DROP TABLE MASTER_DATA.CUST_EXT_LOAD CASCADE;

CREATE CACHED TABLE MASTER_DATA.CUST_EXT_LOAD
(
   CUSTID      VARCHAR(32)            NOT NULL,
   NAME        VARCHAR(1024),
   ADD1        VARCHAR(1024),
   ADD2        VARCHAR(1024),
   ADD3        VARCHAR(1024),
   CITY        VARCHAR(1024),
   STATEPROV   VARCHAR(16),
   COUNTRY     VARCHAR(32),
   POSTCODE    VARCHAR(32),
   CREATEDATE  BIGINT,
   TERMS       TINYINT,
   CREDITLIM   BIGINT,
   TTMREV      DECIMAL(65535,32767),
   SFID        VARCHAR(64),
   CORPCODE    CHAR(1),
   CRLIMDATE   BIGINT,
   ACCTSTAT    CHAR(1),
   ACCTTYPE    CHAR(1),
   BONDTYPE    CHAR(1),
   PREVCO      CHAR(2),
   SIC         CHAR(4),
   CST         VARCHAR(32),
   CSM         VARCHAR(128),
   MSD         VARCHAR(128),
   SC          VARCHAR(128),
   WAIVERTYPE  VARCHAR(256),
   INVCURR     CHAR(3),
   CREDITCODE  VARCHAR(3),
   LANGUAGE    VARCHAR(32),
   PARENT      VARCHAR(32),
   REMITTO     TINYINT,
   REMARKS1    VARCHAR(128),
   REMARKS2    VARCHAR(128)
);

ALTER TABLE MASTER_DATA.CUST_EXT_LOAD
   ADD PRIMARY KEY (CUSTID);

DROP TABLE MASTER_DATA.CUST_OVER_LOAD CASCADE;

CREATE CACHED TABLE MASTER_DATA.CUST_OVER_LOAD
(
   CUSTID      VARCHAR(32)            NOT NULL,
   NAME        VARCHAR(1024),
   ADD1        VARCHAR(1024),
   ADD2        VARCHAR(1024),
   ADD3        VARCHAR(1024),
   CITY        VARCHAR(1024),
   STATEPROV   VARCHAR(16),
   COUNTRY     VARCHAR(32),
   POSTCODE    VARCHAR(32),
   CREATEDATE  BIGINT,
   TERMS       TINYINT,
   CREDITLIM   BIGINT,
   TTMREV      DECIMAL(65535,32767),
   SFID        VARCHAR(64),
   CORPCODE    CHAR(1),
   CRLIMDATE   BIGINT,
   ACCTSTAT    CHAR(1),
   ACCTTYPE    CHAR(1),
   BONDTYPE    CHAR(1),
   PREVCO      CHAR(2),
   SIC         CHAR(4),
   CST         VARCHAR(32),
   CSM         VARCHAR(128),
   MSD         VARCHAR(128),
   SC          VARCHAR(128),
   WAIVERTYPE  VARCHAR(256),
   INVCURR     CHAR(3),
   CREDITCODE  VARCHAR(3),
   LANGUAGE    VARCHAR(32),
   PARENT      VARCHAR(32),
   REMITTO     TINYINT,
   REMARKS1    VARCHAR(128),
   REMARKS2    VARCHAR(128)
);

ALTER TABLE MASTER_DATA.CUST_OVER_LOAD
   ADD PRIMARY KEY (CUSTID);
