DROP SCHEMA LIVINGSTON_AR;

CREATE SCHEMA LIVINGSTON_AR;

CREATE TABLE LIVINGSTON_AR.AR_ITEM_MASTER
(
   CMPCODE       VARCHAR(4)    NOT NULL,
   CUSTID        VARCHAR(32)   NOT NULL,
   DOCTYPE       VARCHAR(32)   NOT NULL,
   DOCSUBTYPE    VARCHAR(8),
   DOCNUM        BIGINT        NOT NULL,
   SOURCESYS     VARCHAR(32),
   INVOICEREF    VARCHAR(32),
   GLACCT        BIGINT,
   DOCDATE       DATE          NOT NULL,
   POSTDATE      DATE          NOT NULL,
   CLEARDATE     DATETIME      NULL DEFAULT NULL,
   DOCDESC       VARCHAR(48),
   XACTREF       VARCHAR(32),
   CUSTREF       VARCHAR(32),
   EXTREF5       VARCHAR(32),
   DOCCURR       VARCHAR(3),
   HOMECURR      VARCHAR(3),
   ALTCURR       VARCHAR(3),
   ORGVAL_DOC    DECIMAL(20,2),
   ORGVAL_HOME   DECIMAL(20,2),
   ORGVAL_ALT    DECIMAL(20,2),
   ORGVAL_NORM   DECIMAL(20,2),
   OPENVAL_DOC   DECIMAL(20,2),
   OPENVAL_HOME  DECIMAL(20,2),
   OPENVAL_ALT   DECIMAL(20,2),
   OPENVAL_NORM  DECIMAL(20,2),
   PAYVAL_DOC    DECIMAL(20,2),
   PAYVAL_HOME   DECIMAL(20,2),
   PAYVAL_ALT    DECIMAL(20,2),
   PAYVAL_NORM   DECIMAL(20,2),
   K84ACCTDATE   DATE           NULL DEFAULT NULL,
   DUEDATE       DATE           NULL DEFAULT NULL,
   LASTMOD       TIMESTAMP      DEFAULT NOW()
);

ALTER TABLE LIVINGSTON_AR.AR_ITEM_MASTER
   ADD PRIMARY KEY (CMPCODE, DOCTYPE, DOCNUM, CUSTID);

CREATE INDEX IDX_AR_ITEM_CLEARED
   ON LIVINGSTON_AR.AR_ITEM_MASTER (CLEARDATE ASC);

CREATE INDEX IDX_AR_ITEM_XACT
   ON LIVINGSTON_AR.AR_ITEM_MASTER (XACTREF ASC);

CREATE INDEX IDX_AR_ITEM_CURR
   ON LIVINGSTON_AR.AR_ITEM_MASTER (DOCCURR ASC, HOMECURR ASC, ALTCURR ASC);

CREATE TABLE LIVINGSTON_AR.CUSTOMER_MASTER
(
   CUSTID      VARCHAR(32)     NOT NULL,
   NAME        VARCHAR(1024),
   ADD1        VARCHAR(1024),
   ADD2        VARCHAR(1024),
   ADD3        VARCHAR(1024),
   CITY        VARCHAR(1024),
   STATEPROV   VARCHAR(16),
   COUNTRY     VARCHAR(32),
   POSTCODE    VARCHAR(32),
   CREATEDATE  DATE,
   TERMS       TINYINT,
   CREDITLIM   DECIMAL(20,2),
   TTMREV      DECIMAL(20,2),
   SFID        VARCHAR(64),
   CORPCODE    CHAR(1),
   CRLIMDATE   DATE,
   ACCTSTAT    CHAR(1),
   ACCTTYPE    CHAR(1),
   BONDTYPE    CHAR(1),
   PREVCO      CHAR(2),
   SIC         CHAR(4),
   CST         VARCHAR(32),
   CSM         VARCHAR(128),
   MSD         VARCHAR(128),
   SC          VARCHAR(128),
   WAIVERTYPE  VARCHAR(256),
   INVCURR     CHAR(3),
   CREDITCODE  VARCHAR(3),
   LANGUAGE    VARCHAR(32),
   PARENT      VARCHAR(32),
   REMITTO     TINYINT,
   REMARKS1    VARCHAR(128),
   REMARKS2    VARCHAR(128),
   LASTARACT   TIMESTAMP     NULL DEFAULT NULL,
   LASTMOD     TIMESTAMP     DEFAULT NOW(),
   GPARENT     VARCHAR(32)   DEFAULT NULL,
   GGPARENT    VARCHAR(32)   DEFAULT NULL,
   GGGPARENT   VARCHAR(32)   DEFAULT NULL
);

ALTER TABLE LIVINGSTON_AR.CUSTOMER_MASTER
   ADD PRIMARY KEY (CUSTID);

CREATE INDEX IDX_CUST_PARENT
   ON LIVINGSTON_AR.CUSTOMER_MASTER (PARENT ASC);

CREATE TABLE LIVINGSTON_AR.K84_MASTER
(
   XACTID    VARCHAR(32)    NOT NULL,
   RPTDATE   TIMESTAMP,
   ACCTDATE  TIMESTAMP,
   SECID     INT             NOT NULL
);

ALTER TABLE LIVINGSTON_AR.K84_MASTER
   ADD PRIMARY KEY (XACTID);

CREATE TABLE LIVINGSTON_AR.AR_SETTLEMENT_MASTER
(
   CMPCODE    VARCHAR(4)    NOT NULL,
   CUSTID     VARCHAR(32)   NOT NULL,
   DOCTYPE    VARCHAR(32)   NOT NULL,
   DOCNUM     BIGINT        NOT NULL,
   MATCHREF   BIGINT        NOT NULL,
   PAYDATE    TIMESTAMP,
   PAYVAL_DOC DOUBLE        DEFAULT 0,
   DOCCURR    VARCHAR(3),
   LASTMOD    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_AR_SETTLEMENT 
   ON LIVINGSTON_AR.AR_SETTLEMENT_MASTER(CMPCODE, CUSTID, DOCTYPE, DOCNUM, MATCHREF);

CREATE TABLE LIVINGSTON_AR.CUST_HIERARCHY
(
  CUSTID VARCHAR(32) NOT NULL,
  L1     VARCHAR(32) NOT NULL,
  L2     VARCHAR(32) DEFAULT NULL,
  L3     VARCHAR(32) DEFAULT NULL,
  L4     VARCHAR(32) DEFAULT NULL,
  L5     VARCHAR(32) DEFAULT NULL
);

ALTER TABLE LIVINGSTON_AR.CUST_HIERARCHY
   ADD PRIMARY KEY (CUSTID);